name: Wallet Adapter Pipeline

on:
  pull_request:
    branches:
      - 'collaborate/adapter/**'
  push:
    branches:
      - 'collaborate/adapter/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run adapter validation script
        run: node scripts/validate-adapter.js ${{ github.ref_name }}
      
      - name: Run wallet unit tests
        run: npm run test:wallet

  sync-to-bitbucket:
    needs: validate
    if: github.event_name == 'push' && contains(github.ref, 'collaborate/adapter/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract adapter name
        id: extract
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ADAPTER_NAME=${BRANCH_NAME#collaborate/adapter/}
          echo "adapter_name=$ADAPTER_NAME" >> $GITHUB_OUTPUT
      
      - name: Push to Bitbucket
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.BITBUCKET_REPO_URL }}
          ssh_private_key: ${{ secrets.BITBUCKET_SSH_KEY }}
          ssh_username: ${{ secrets.BITBUCKET_USERNAME }}
          target_branch: "github/${{ steps.extract.outputs.adapter_name }}"